package com.fabiel.weather.core;

import android.app.Application;

/**
 * Android application used to keep the instance of the Dagger application component (or application
 * graph).
 */
public final class WeatherApplication extends Application {

  private ApplicationComponent applicationComponent;

  @Override
  public void onCreate() {
    super.onCreate();
    // DaggerApplicationComponent is autogenerated by Dagger based on
    // com.fabiel.weather.core.ApplicationComponent
    this.applicationComponent = DaggerApplicationComponent.create();
  }

  /** @return the Dagger application component (or application graph) */
  public ApplicationComponent getApplicationComponent() {
    return this.applicationComponent;
  }
}
